### ISSUE TITLE
Customize output format other than JSON

### ISSUE THREAD

**Issue by geekyme** [yahoo/babel-plugin-react-intl#57]
How do I output like a .yaml file like the below? Setting `key`, `title`, and `value` to the values of react-intl, `id`, `description`, `defaultMessage` respectively. 

```
- translation:
    key: "some.path.to.component"
    title: "Lorem ipsum"
    value: "Blah blah blah"
```
